"use strict";
const STORAGE_KEY="field-area-drawings-v2",OLD_KEY="field-area-records-v1";
const $=id=>document.getElementById(id);const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const state={mode:"triangle",shapes:[],selectedEdge:null,recordId:null,records:loadRecords(),confirmAction:null,deferredInstall:null,viewBox:"0 0 700 430"};
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function num(id){return Number($(id).value)}function fmt(v){return Number(v).toLocaleString("ja-JP",{minimumFractionDigits:3,maximumFractionDigits:3})}function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}function midpoint(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}function samePoint(a,b){return dist(a,b)<1e-6}function sameEdge(a,b,c,d){return(samePoint(a,c)&&samePoint(b,d))||(samePoint(a,d)&&samePoint(b,c))}
function polygonArea(points){let s=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];s+=a.x*b.y-b.x*a.y}return Math.abs(s)/2}
function centroid(points){return{x:points.reduce((s,p)=>s+p.x,0)/points.length,y:points.reduce((s,p)=>s+p.y,0)/points.length}}
function alignment(){return document.querySelector('input[name="alignment"]:checked').value}
function shapeEdges(shape){return shape.points.map((p,i)=>({shapeId:shape.id,index:i,a:p,b:shape.points[(i+1)%shape.points.length]}))}
function freeEdges(){const all=state.shapes.flatMap(shapeEdges);return all.filter((e,i)=>!all.some((o,j)=>j!==i&&sameEdge(e.a,e.b,o.a,o.b)))}
function edgeByKey(key){return freeEdges().find(e=>`${e.shapeId}:${e.index}`===key)}
function outwardNormal(edge,flip=false){const dx=edge.b.x-edge.a.x,dy=edge.b.y-edge.a.y,l=Math.hypot(dx,dy),left={x:-dy/l,y:dx/l};const parent=state.shapes.find(s=>s.id===edge.shapeId),c=centroid(parent.points);const cross=dx*(c.y-edge.a.y)-dy*(c.x-edge.a.x);let sign=cross>0?-1:1;if(flip)sign*=-1;return{x:left.x*sign,y:left.y*sign}}
function makeTriangle(a,b,c,edge=null,flip=false){if(![a,b,c].every(v=>Number.isFinite(v)&&v>0))throw Error("すべての辺に0より大きい数値を入力してください。");if(a+b<=c||a+c<=b||b+c<=a)throw Error("この3辺では三角形が成立しません。");let p0={x:0,y:0},p1={x:c,y:0},normal={x:0,y:-1};if(edge){p0={...edge.a};p1={...edge.b};normal=outwardNormal(edge,flip)}const u={x:(p1.x-p0.x)/c,y:(p1.y-p0.y)/c};const x=(b*b+c*c-a*a)/(2*c),h=Math.sqrt(Math.max(0,b*b-x*x));const apex={x:p0.x+u.x*x+normal.x*h,y:p0.y+u.y*x+normal.y*h};return{id:uid(),type:"triangle",points:[p0,p1,apex],area:Math.sqrt(((a+b+c)/2)*(((a+b+c)/2)-a)*(((a+b+c)/2)-b)*(((a+b+c)/2)-c)),dimensions:{a,b,c},alignment:null}}
function makeTrapezoid(top,bottom,h,align,edge=null,flip=false){if(![top,bottom,h].every(v=>Number.isFinite(v)&&v>0))throw Error("上底・下底・高さに0より大きい数値を入力してください。");let p0={x:0,y:0},p1={x:bottom,y:0},normal={x:0,y:-1};if(edge){p0={...edge.a};p1={...edge.b};normal=outwardNormal(edge,flip);bottom=dist(p0,p1)}const u={x:(p1.x-p0.x)/bottom,y:(p1.y-p0.y)/bottom};const offset=align==="left"?0:align==="right"?bottom-top:(bottom-top)/2;const q0={x:p0.x+u.x*offset+normal.x*h,y:p0.y+u.y*offset+normal.y*h};const q1={x:q0.x+u.x*top,y:q0.y+u.y*top};return{id:uid(),type:"trapezoid",points:[p0,p1,q1,q0],area:(top+bottom)*h/2,dimensions:{top,bottom,height:h},alignment:align}}
function loadRecords(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");if(Array.isArray(v))return v}catch{}return[]}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.records))}
function total(){return state.shapes.reduce((s,v)=>s+Number(v.area),0)}
function color(i){return["#dce879","#a9d8c3","#f2c98b","#bfc9eb","#e6b8c5","#c9df9c"][i%6]}
function fitView(){if(!state.shapes.length){state.viewBox="0 0 700 430";return}const pts=state.shapes.flatMap(s=>s.points),xs=pts.map(p=>p.x),ys=pts.map(p=>p.y);let minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const w=Math.max(maxX-minX,1),h=Math.max(maxY-minY,1),pad=Math.max(w,h)*.22;state.viewBox=`${minX-pad} ${minY-pad} ${w+pad*2} ${h+pad*2}`}
function renderCanvas(autoFit=false){if(autoFit)fitView();const svg=$("drawingCanvas");svg.setAttribute("viewBox",state.viewBox);if(!state.shapes.length){svg.innerHTML='<text x="350" y="205" text-anchor="middle" fill="#829189" font-size="18">ここに連続図面が表示されます</text><text x="350" y="235" text-anchor="middle" fill="#9aa69f" font-size="12">寸法を入力して最初の図形を追加</text>';return}const vb=state.viewBox.split(/\s+/).map(Number),scale=Math.max(vb[2],vb[3]),labelSize=scale*.045,edgeSize=scale*.025,labelOffset=scale*.012,halo=scale*.006;const free=freeEdges(),selected=state.selectedEdge;let html="";state.shapes.forEach((s,i)=>{const pts=s.points.map(p=>`${p.x},${p.y}`).join(" "),c=centroid(s.points);html+=`<polygon class="shape-polygon" points="${pts}" fill="${color(i)}" fill-opacity=".78"/><text class="shape-label" style="font-size:${labelSize}px" x="${c.x}" y="${c.y}">${i+1}</text>`;shapeEdges(s).forEach(e=>{const m=midpoint(e.a,e.b);html+=`<text class="edge-length" style="font-size:${edgeSize}px;stroke-width:${halo}px" x="${m.x}" y="${m.y-labelOffset}">${dist(e.a,e.b).toFixed(2)}m</text>`})});free.forEach(e=>{const key=`${e.shapeId}:${e.index}`;html+=`<line class="edge-line ${selected===key?"selected":""}" x1="${e.a.x}" y1="${e.a.y}" x2="${e.b.x}" y2="${e.b.y}"/><line class="edge-hit" data-edge="${key}" x1="${e.a.x}" y1="${e.a.y}" x2="${e.b.x}" y2="${e.b.y}"/>`});svg.innerHTML=html}
function refreshEdgeOptions(){const edges=freeEdges(),old=state.selectedEdge;if(!edges.length){state.selectedEdge=null;return}if(!edges.some(e=>`${e.shapeId}:${e.index}`===old))state.selectedEdge=`${edges[0].shapeId}:${edges[0].index}`;$("edgeSelect").innerHTML=edges.map(e=>{const si=state.shapes.findIndex(s=>s.id===e.shapeId)+1,key=`${e.shapeId}:${e.index}`;return`<option value="${key}" ${key===state.selectedEdge?"selected":""}>図形 ${si}・辺 ${e.index+1}（${dist(e.a,e.b).toFixed(3)} m）</option>`}).join("");applySharedLength()}
function applySharedLength(){const edge=edgeByKey(state.selectedEdge);if(!edge)return;const l=dist(edge.a,edge.b);$("sideC").value=l.toFixed(6);$("bottomBase").value=l.toFixed(6)}
function renderParts(){$("partsSection").classList.toggle("hidden",!state.shapes.length);$("partsList").innerHTML=state.shapes.map((s,i)=>`<div class="part-row"><span class="part-number">${i+1}</span><div><strong>${s.type==="triangle"?"三角形":"台形"}${s.type==="trapezoid"?`・${{left:"左",center:"中央",right:"右"}[s.alignment]}揃え`:""}</strong><small>${dimensionText(s)}</small></div><div class="part-area">${fmt(s.area)} m²</div></div>`).join("")}
function dimensionText(s){const d=s.dimensions;return s.type==="triangle"?`a ${d.a}m / b ${d.b}m / c ${d.c}m`:`上底 ${d.top}m / 下底 ${d.bottom}m / 高さ ${d.height}m`}
function refresh(){const has=state.shapes.length>0;$("connectionPanel").classList.toggle("hidden",!has);$("flipField").classList.toggle("hidden",!has);$("stepNumber").textContent=has?"2":"1";$("sideC").readOnly=has;$("bottomBase").readOnly=has;$("sideCLabel").textContent=has?"接続辺 c":"辺 c";$("bottomBaseLabel").textContent=has?"接続辺（下底）":"下底";$("shapeCount").textContent=state.shapes.length;$("drawingTotal").textContent=fmt(total());$("printButton").disabled=!has;$("canvasHint").textContent=has?"緑色の外周辺をタップして次の接続先を選択":"最初の図形を追加してください";refreshEdgeOptions();renderCanvas(true);renderParts()}
function clearInputs(){["sideA","sideB","sideC","topBase","bottomBase","height"].forEach(id=>$(id).value="");$("flipDirection").checked=false;document.querySelector('input[name="alignment"][value="center"]').checked=true;$("message").textContent="";applySharedLength()}
function setMode(mode){state.mode=mode;document.querySelectorAll(".mode").forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle("active",on);b.setAttribute("aria-checked",String(on))});$("triangleFields").classList.toggle("hidden",mode!=="triangle");$("trapezoidFields").classList.toggle("hidden",mode!=="trapezoid");clearInputs()}
function addShape(){try{const edge=state.shapes.length?edgeByKey(state.selectedEdge):null;if(state.shapes.length&&!edge)throw Error("接続する辺を選択してください。");const flip=$("flipDirection").checked;let shape;if(state.mode==="triangle"){shape=makeTriangle(num("sideA"),num("sideB"),edge?dist(edge.a,edge.b):num("sideC"),edge,flip)}else{shape=makeTrapezoid(num("topBase"),edge?dist(edge.a,edge.b):num("bottomBase"),num("height"),alignment(),edge,flip)}state.shapes.push(shape);clearInputs();refresh();showToast(`図形 ${state.shapes.length} を追加しました`)}catch(e){$("message").textContent=e.message}}
function resetDrawing(){state.shapes=[];state.selectedEdge=null;state.recordId=null;$("name").value="";$("date").value=today();$("memo").value="";$("saveDrawingButton").textContent="図面を保存";setMode("triangle");refresh()}
function ask(title,text,action){state.confirmAction=action;$("confirmTitle").textContent=title;$("confirmText").textContent=text;$("confirmDialog").showModal()}
function saveDrawing(){const name=$("name").value.trim();if(!name){showToast("名称・測点名を入力してください");$("name").focus();return}if(!state.shapes.length){showToast("図形を1つ以上追加してください");return}const now=new Date().toISOString(),record={id:state.recordId||uid(),name,date:$("date").value||today(),memo:$("memo").value.trim(),shapes:structuredClone(state.shapes),total:total(),createdAt:now,updatedAt:now};const i=state.records.findIndex(r=>r.id===record.id);if(i>=0){record.createdAt=state.records[i].createdAt;state.records[i]=record}else state.records.unshift(record);state.recordId=record.id;persist();renderHistory();$("saveDrawingButton").textContent="変更を保存";showToast(i>=0?"図面を更新しました":"図面を保存しました")}
function editRecord(id){const r=state.records.find(x=>x.id===id);if(!r)return;state.recordId=r.id;state.shapes=structuredClone(r.shapes);$("name").value=r.name;$("date").value=r.date;$("memo").value=r.memo||"";$("saveDrawingButton").textContent="変更を保存";refresh();switchView("drawing")}
function renderHistory(){$("historyCount").textContent=state.records.length;$("emptyState").classList.toggle("hidden",state.records.length>0);$("historyList").innerHTML=state.records.map(r=>`<article class="record"><div class="record-main"><button type="button" data-edit="${r.id}"><div class="record-name">${esc(r.name)}</div><div class="record-meta">${esc(r.date)} ｜ ${r.shapes.length}図形${r.memo?`<br>${esc(r.memo)}`:""}</div></button></div><div><div class="record-area">${fmt(r.total)} <small>m²</small></div><div class="history-buttons"><button type="button" data-pdf="${r.id}">PDF</button><button type="button" data-edit="${r.id}">編集</button><button type="button" class="delete" data-delete="${r.id}">削除</button></div></div></article>`).join("")}
function switchView(view){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("drawingView").classList.toggle("active",view==="drawing");$("historyView").classList.toggle("active",view==="history");if(view==="history")renderHistory();window.scrollTo({top:0,behavior:"smooth"})}
function printRecord(record=null){const r=record||{name:$("name").value.trim()||"未保存の図面",date:$("date").value||today(),memo:$("memo").value.trim(),shapes:state.shapes,total:total()};if(!r.shapes.length)return;const oldShapes=state.shapes,oldEdge=state.selectedEdge,oldVB=state.viewBox;state.shapes=r.shapes;state.selectedEdge=null;fitView();renderCanvas(false);const svg=$("drawingCanvas").outerHTML.replace('id="drawingCanvas"','class="print-svg"');state.shapes=oldShapes;state.selectedEdge=oldEdge;state.viewBox=oldVB;renderCanvas(false);$("printSheet").innerHTML=`<h1>現場面積図面</h1><div class="print-meta"><div><b>名称・測点名：</b>${esc(r.name)}</div><div><b>日付：</b>${esc(r.date)}</div></div>${svg}<table><thead><tr><th>No.</th><th>図形</th><th>寸法</th><th>面積</th></tr></thead><tbody>${r.shapes.map((s,i)=>`<tr><td>${i+1}</td><td>${s.type==="triangle"?"三角形":"台形"}</td><td>${esc(dimensionText(s))}</td><td>${fmt(s.area)} m²</td></tr>`).join("")}</tbody></table><div class="print-total">合計面積 ${fmt(r.total)} m²</div>${r.memo?`<div class="print-note"><b>メモ：</b><br>${esc(r.memo)}</div>`:""}<footer>現場面積ノート</footer>`;window.print()}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}function csvCell(v){return`"${String(v??"").replace(/"/g,'""')}"`}
function exportCsv(){if(!state.records.length)return showToast("出力する記録がありません");const head=["名称・測点名","日付","図形数","合計面積(m²)","メモ"],rows=state.records.map(r=>[r.name,r.date,r.shapes.length,r.total,r.memo].map(csvCell).join(","));download(`現場面積_${today()}.csv`,"\uFEFF"+[head.map(csvCell).join(","),...rows].join("\r\n"),"text/csv;charset=utf-8")}
function exportJson(){download(`現場面積バックアップ_${today()}.json`,JSON.stringify({app:"現場面積ノート",version:2,exportedAt:new Date().toISOString(),records:state.records},null,2),"application/json")}
async function importJson(file){try{const data=JSON.parse(await file.text());if(!data||!Array.isArray(data.records)||!data.records.every(r=>r.id&&r.name&&Array.isArray(r.shapes)))throw Error();const map=new Map(state.records.map(r=>[r.id,r]));data.records.forEach(r=>map.set(r.id,r));state.records=[...map.values()].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));persist();renderHistory();showToast(`${data.records.length}件を復元しました`)}catch{showToast("このバックアップは読み込めません")}finally{$("importJsonInput").value=""}}
function showToast(text){const t=$("toast");t.textContent=text;t.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove("show"),2200)}

const SpeechRecognitionClass=window.SpeechRecognition;
const offlineSpeechSupported=!!(SpeechRecognitionClass&&typeof SpeechRecognitionClass.available==="function"&&typeof SpeechRecognitionClass.install==="function");
const iOSKeyboardDictation=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1);
const mobileKeyboardDictation=/Android|iPad|iPhone|iPod/i.test(navigator.userAgent)||navigator.maxTouchPoints>0;
const VOICE_FIELDS=[
  {id:"name",label:"名称・測点名",type:"text"},
  {id:"sideA",label:"辺 a",type:"number"},{id:"sideB",label:"辺 b",type:"number"},{id:"sideC",label:"辺 c",type:"number"},
  {id:"topBase",label:"上底",type:"number"},{id:"bottomBase",label:"下底",type:"number"},{id:"height",label:"高さ",type:"number"},
  {id:"memo",label:"現場メモ",type:"text"}
];
let voiceRecognition=null,voiceTarget=null,voiceDefinition=null,voiceHandled=false,offlineSpeechReady=false;
function parseSpokenMeasurement(text){
  let s=String(text||"").normalize("NFKC").toLowerCase().replace(/[、，]/g,",").replace(/[。．]/g,".").replace(/てん/g,"点").trim();
  const unit=s.match(/(-?\d+(?:\.\d+)?)\s*(?:m|メートル)(?:\s*(\d+(?:\.\d+)?)\s*(?:cm|センチ(?:メートル)?))?/i);
  if(unit){const meters=Number(unit[1]),centimeters=unit[2]===undefined?0:Number(unit[2]);if(Number.isFinite(meters)&&Number.isFinite(centimeters))return Number((meters+centimeters/100).toFixed(6))}
  s=s.replace(/[点]/g,".").replace(/(?:メートル|m|センチメートル|センチ|cm)/gi,"").replace(/,/g,"");
  const match=s.match(/-?\d+(?:\.\d+)?/);if(!match)return null;const value=Number(match[0]);return Number.isFinite(value)?value:null
}
function voiceErrorMessage(code){return({"not-allowed":"マイクの使用が許可されていません。ブラウザの設定でマイクを許可してください。","service-not-allowed":"この端末では端末内音声認識を利用できません。","language-not-supported":"日本語のオフライン音声パックが準備されていません。","no-speech":"音声を聞き取れませんでした。もう一度お試しください。","audio-capture":"マイクを使用できません。","network":"オフライン音声パックを利用できませんでした。"})[code]||"音声入力を開始できませんでした。"}
function setListening(on){document.querySelectorAll(".voice-button").forEach(b=>b.classList.toggle("listening",on&&b.dataset.voiceTarget===voiceTarget?.id));let indicator=document.querySelector(".voice-listening");if(on&&!indicator){indicator=document.createElement("div");indicator.className="voice-listening";indicator.textContent="聞き取り中… 話してください";document.body.appendChild(indicator)}if(!on&&indicator)indicator.remove()}
function stopVoiceRecognition(){if(voiceRecognition){voiceRecognition.onend=null;voiceRecognition.onerror=null;try{voiceRecognition.abort()}catch{}voiceRecognition=null}setListening(false)}
function showVoicePreview(transcript){
  $("voiceTranscript").textContent=transcript;$("voiceDialogTitle").textContent=`${voiceDefinition.label}の確認`;$("voiceMessage").textContent="";
  if(voiceDefinition.type==="number"){const value=parseSpokenMeasurement(transcript);$("voiceValueLabel").textContent="入力する数値（m）";$("voiceValue").inputMode="decimal";$("voiceValue").value=value===null?"":String(value);if(value===null)$("voiceMessage").textContent="数値を認識できませんでした。手直しするか、もう一度お試しください。"}
  else{$("voiceValueLabel").textContent="入力する内容";$("voiceValue").inputMode="text";$("voiceValue").value=transcript}
  $("voiceDialog").showModal();setTimeout(()=>$("voiceValue").focus(),50)
}
function startVoiceInput(target,definition){
  if(!offlineSpeechSupported||!window.isSecureContext){showToast("この端末ではオフライン音声入力を利用できません");return}if(!offlineSpeechReady){showToast("先にオフライン音声を準備してください");return}stopVoiceRecognition();voiceTarget=target;voiceDefinition=definition;voiceHandled=false;
  const recognition=new SpeechRecognitionClass();voiceRecognition=recognition;recognition.lang="ja-JP";recognition.processLocally=true;recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=1;
  recognition.onresult=e=>{voiceHandled=true;const transcript=Array.from(e.results).map(r=>r[0].transcript).join(" ").trim();setListening(false);voiceRecognition=null;if(transcript)showVoicePreview(transcript);else showToast("音声を聞き取れませんでした")};
  recognition.onerror=e=>{voiceHandled=true;setListening(false);voiceRecognition=null;showToast(voiceErrorMessage(e.error))};
  recognition.onend=()=>{setListening(false);voiceRecognition=null;if(!voiceHandled)showToast("音声を聞き取れませんでした")};
  try{recognition.start();setListening(true)}catch{voiceRecognition=null;setListening(false);showToast("音声入力を開始できませんでした")}
}
function syncVoiceButtons(){document.querySelectorAll(".voice-button").forEach(button=>{const target=$(button.dataset.voiceTarget);button.hidden=!mobileKeyboardDictation;button.disabled=!!target?.readOnly;button.textContent="🎙"})}
function updateOfflineSpeechUi(status){const help=$("voiceHelp"),setup=$("offlineSpeechSetup");if(!help||!setup)return;help.classList.toggle("unsupported",!iOSKeyboardDictation&&(status==="unsupported"||status==="unavailable"||status==="error"));setup.hidden=true;setup.disabled=false;setup.dataset.action="check";if(status==="available"){offlineSpeechReady=true;help.querySelector("span").textContent="🎙️ オフライン音声入力を使用できます。認識結果を確認してから反映します。"}else if(status==="downloadable"){offlineSpeechReady=false;help.querySelector("span").textContent="初回のみ、日本語のオフライン音声パックをダウンロードしてください。";setup.textContent="オフライン音声を準備";setup.dataset.action="install";setup.hidden=false}else if(status==="downloading"){offlineSpeechReady=false;help.querySelector("span").textContent="日本語の音声パックをダウンロードしています。完了後に再確認してください。";setup.textContent="状態を再確認";setup.hidden=false}else if(iOSKeyboardDictation){offlineSpeechReady=false;help.querySelector("span").textContent="iPhoneでは⌨️を押して入力欄を開き、キーボードのマイクを押してください。"}else if(status==="unavailable"){offlineSpeechReady=false;help.querySelector("span").textContent="この端末では日本語のオフライン音声入力を利用できません。手入力をご利用ください。"}else if(status==="checking"){offlineSpeechReady=false;help.querySelector("span").textContent="オフライン音声入力を確認しています…"}else if(status==="error"){offlineSpeechReady=false;help.querySelector("span").textContent="オフライン音声の状態を確認できませんでした。";setup.textContent="状態を再確認";setup.hidden=false}else{offlineSpeechReady=false;help.querySelector("span").textContent="この端末・ブラウザはオフライン音声入力に対応していません。手入力をご利用ください。"}syncVoiceButtons()}
function startIOSKeyboardDictation(target){target.focus();try{target.setSelectionRange(target.value.length,target.value.length)}catch{}target.scrollIntoView({behavior:"smooth",block:"center"});showToast("iPhoneキーボードのマイクを押してください")}
function startMobileKeyboardDictation(target){target.focus();try{target.setSelectionRange(target.value.length,target.value.length)}catch{}target.scrollIntoView({behavior:"smooth",block:"center"});showToast("スマホキーボードのマイクを押してください")}
async function checkOfflineSpeech(){if(!offlineSpeechSupported||!window.isSecureContext){updateOfflineSpeechUi("unsupported");return}updateOfflineSpeechUi("checking");try{const status=await SpeechRecognitionClass.available({langs:["ja-JP"],processLocally:true});updateOfflineSpeechUi(status)}catch{updateOfflineSpeechUi("error")}}
async function installOfflineSpeech(){const button=$("offlineSpeechSetup");button.disabled=true;button.textContent="ダウンロード中…";try{const installed=await SpeechRecognitionClass.install({langs:["ja-JP"],processLocally:true});if(installed){await checkOfflineSpeech();showToast(offlineSpeechReady?"オフライン音声の準備が完了しました":"音声パックを確認しています")}else{updateOfflineSpeechUi("error");showToast("日本語の音声パックをダウンロードできませんでした")}}catch{updateOfflineSpeechUi("error");showToast("通信できる場所で、もう一度準備してください")}}
function setupVoiceInput(){
  if(!mobileKeyboardDictation)return;const help=document.createElement("div");help.className="voice-help";help.textContent="🎙️ 入力欄のボタンを押し、スマホキーボードのマイクを押してください。";document.querySelector(".add-card .mode-switch").after(help);
  VOICE_FIELDS.forEach(def=>{const target=$(def.id);if(!target)return;const holder=target.closest(".with-unit")||target.closest(".field");if(!holder||holder.querySelector(`[data-voice-target="${def.id}"]`))return;holder.classList.add("voice-field");const button=document.createElement("button");button.type="button";button.className="voice-button";button.dataset.voiceTarget=def.id;button.setAttribute("aria-label",`${def.label}をスマホの音声入力で入力`);button.title=`${def.label}を音声入力`;button.textContent="🎙";button.addEventListener("click",()=>{if(target.readOnly){showToast("接続辺の長さは図面から自動入力されます");return}startMobileKeyboardDictation(target)});holder.appendChild(button)});syncVoiceButtons()
}
$("voiceCancelButton").addEventListener("click",()=>$("voiceDialog").close());
$("voiceRetryButton").addEventListener("click",()=>{const target=voiceTarget,definition=voiceDefinition;$("voiceDialog").close();if(target&&definition)startVoiceInput(target,definition)});
$("voiceApplyButton").addEventListener("click",()=>{if(!voiceTarget||!voiceDefinition)return;const value=$("voiceValue").value.trim();if(!value){$("voiceMessage").textContent="入力する内容を確認してください。";return}if(voiceDefinition.type==="number"){const number=Number(value);if(!Number.isFinite(number)||number<=0){$("voiceMessage").textContent="0より大きい数値を入力してください。";return}voiceTarget.value=String(number)}else voiceTarget.value=value;voiceTarget.dispatchEvent(new Event("input",{bubbles:true}));$("voiceDialog").close();voiceTarget.focus();showToast(`${voiceDefinition.label}に入力しました`)});
$("voiceDialog").addEventListener("cancel",()=>stopVoiceRecognition());
const refreshWithoutVoice=refresh;refresh=function(){refreshWithoutVoice();syncVoiceButtons()};
setupVoiceInput();
document.querySelectorAll(".mode").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));$("edgeSelect").addEventListener("change",e=>{state.selectedEdge=e.target.value;applySharedLength();renderCanvas(false)});$("drawingCanvas").addEventListener("click",e=>{const hit=e.target.closest("[data-edge]");if(!hit)return;state.selectedEdge=hit.dataset.edge;refreshEdgeOptions();renderCanvas(false);showToast("接続辺を選択しました")});$("fitButton").addEventListener("click",()=>renderCanvas(true));$("addShapeButton").addEventListener("click",addShape);$("undoButton").addEventListener("click",()=>ask("最後の図形を戻しますか？","最後に追加した図形と、その接続を削除します。",()=>{state.shapes.pop();refresh();showToast("最後の図形を戻しました")}));$("newButton").addEventListener("click",()=>state.shapes.length?ask("新しい図面を作りますか？","未保存の変更は失われます。",resetDrawing):resetDrawing());$("saveDrawingButton").addEventListener("click",saveDrawing);$("printButton").addEventListener("click",()=>printRecord());
$("historyList").addEventListener("click",e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]"),pdf=e.target.closest("[data-pdf]");if(edit)editRecord(edit.dataset.edit);if(pdf){const r=state.records.find(x=>x.id===pdf.dataset.pdf);if(r)printRecord(r)}if(del)ask("図面を削除しますか？","削除した図面は元に戻せません。",()=>{state.records=state.records.filter(r=>r.id!==del.dataset.delete);persist();renderHistory();showToast("図面を削除しました")})});$("cancelConfirmButton").addEventListener("click",()=>$("confirmDialog").close());$("acceptConfirmButton").addEventListener("click",()=>{const fn=state.confirmAction;$("confirmDialog").close();state.confirmAction=null;if(fn)fn()});$("exportCsvButton").addEventListener("click",exportCsv);$("exportJsonButton").addEventListener("click",exportJson);$("importJsonInput").addEventListener("change",e=>e.target.files[0]&&importJson(e.target.files[0]));window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferredInstall=e;$("installButton").classList.remove("hidden")});$("installButton").addEventListener("click",async()=>{if(!state.deferredInstall)return;state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$("installButton").classList.add("hidden")});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));$("date").value=today();refresh();renderHistory();
